services:     
  mariadb:
    container_name: web-mariadb-8
    hostname: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: 8_WebCalculatorDb
      MARIADB_USER: webdb
      MARIADB_PASSWORD: password
    ports:
      - "0.0.0.0:5058:3306"
      
  web:
    container_name: web-app-calculator-8
    hostname: app
    build: 8_Calculator/
    depends_on:
      - mariadb
    ports:
      - "0.0.0.0:5008:5008"